### PR TITLE
Push rather than pull

### PR DESCRIPTION
**Pull request by ktg**
Addresses me-box/databox/issues/129

### CODE REVIEW

**Comment by Toshbrown** [comment]
Thanks Kev, I will take a look shortly

**Comment by yousefamar** [comment]
I think it might be good to also get some wider input on making this change. The [app](https://github.com/yousefamar/cis-example-app) and [server](https://github.com/yousefamar/cis-rest-server) that this driver/app combo was originally based off of followed the same model (phone is client, device is server, rather than the other way around). IIRC, the decision to make the switch to have the driver pull rather than get pushed to was a conscious one to make it conform to "the Databox way" so to speak, even though for this particular use case I agree it is a bit awkward, so it could be worth making an exception.

**Comment by yousefamar** [comment]
(not to mention that this could only then work for ["admin" phones](https://github.com/me-box/databox/issues/136) that need to connect/auth to/with the Databox from the outside pushing data to `/ui/:sensor/data` (so through the CM proxy?) which in itself might be ok, but just something I think we should consider)

**Comment by ktg** [comment]
I think it was a bit awkward, but the main reason I have switched it round was because I couldn't get the driver to connect to an app running on iOS.

**Comment by haddadi** [comment]
depends on the sensor type, but especially if the app is not running in
foreground, it might not be possible to get the data unless apple has
approved that access type. We should think about the ideal approach here
(short and long term).

==
Hamed        https://haddadi.github.io <http://www.eecs.qmul.ac.uk/~hamed/>

**Comment by yousefamar** [comment]
For the sake of MozFest and such, perhaps we could keep both endpoints side by side (and just not use the pulling ones), and then later figure out which to remove or what to change?

I also think that in the future, other changes might make many connectivity issues moot, e.g. if the Databox were to become an actual router replacement with built in VPN and DDNS, which would also affect the decision.

**Comment by Toshbrown** [comment]
Let's leave them both in for now, but use the pull ones for the mobile app. Its the most pragmatic approach 👍 

@ktg can you update your PR please?

**Comment by ktg** [comment]
Updated

**Pull request merged**
